all:	example1 example2

clean:
	rm -f *.o example1 example2

example1 : example1.cpp
	c++ -std=c++2a -o example1  example1.cpp -lstdc++

example2 : example2.cpp
	c++ -std=c++2a -o example2  example2.cpp -lstdc++
